dofile(ModPath .. "hooks/ElementWeaponSwitch.lua")
dofile(ModPath .. "hooks/ElementPointChecker.lua")
dofile(ModPath .. "hooks/ElementWave.lua")
dofile(ModPath .. "hooks/ElementAnnouncerGift.lua")
dofile(ModPath .. "hooks/ElementDynamicEnv.lua")
dofile(ModPath .. "hooks/ElementPlayVideo.lua")